[package]
name = "assistant"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
cpal = "0.15.3"
fastembed = "4.3.0"
rustpotter = "3.0.2"
thiserror = "2.0.9"
tts = "0.26.3"
vosk = "0.3.1"
